Perfil/Models/Linguagem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Perfil.Models
{
    public class Linguagem
    {
        public string title { get; set; }
        public string sigla { get; set; }
        public string texto { get; set; }
        public string href { get; set; }

    }
}

Perfil/Controllers/SecureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Perfil.Controllers
{
    public class SecureController : BaseController
    {
        // GET: Secure
        public ActionResult Index()
        {
            if (Request.ServerVariables["HTTP_REMOTEUSER"] != null)
            {
                if (Session["erroAutenticacao"] != null)
                {
                    TempData["error"] = Session["erroAutenticacao"].ToString();
                }
                else
                {
                    Session["shib"] = Request.ServerVariables["HTTP_REMOTEUSER"].ToString();

                    if (Session["returnURL"] != null)
                        return Redirect(Session["returnURL"].ToString());
                }

                return RedirectToAction("Index", "Home");
            }

            return View();
        }
    }
}

Perfil/Views/Shared/_Layout.cshtml
@using Perfil.App_Start
@using Perfil.Models
@using System.Configuration;

@{
    string appTitle = ConfigurationManager.AppSettings["titulo"]; ;
    ViewBag.Titulo = ViewBag.Titulo ?? appTitle;
    ViewBag.Title = ViewBag.Title ?? appTitle;
    ViewBag.Nome = ConfigurationManager.AppSettings["app"];
    Perfil.ViewModels.BaseViewModel LayoutModel = ViewData["LayoutModel"] as Perfil.ViewModels.BaseViewModel;

    Linguagem currentLanguage = ViewBag.Language;

    String base64 = null, imgSrc = null;

    if (Autenticacao.Foto != null)
    {
        base64 = Convert.ToBase64String(Autenticacao.Foto);
        imgSrc = String.Format("data:image/{0};base64,{1}", Autenticacao.FotoFormato, base64);
    }


    bool alternative = Convert.ToBoolean(ConfigurationManager.AppSettings["AlternativeDesign"]);
    string color = ConfigurationManager.AppSettings["color"].ToString();
}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="@ViewBag.Language.sigla">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=9,IE=10,IE=11" />
    <meta name="viewport" content="width=device-width, user-scalable=no" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <title>@ViewBag.Title</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    @Styles.Render("~/Content/Site.css")
    @Styles.Render("~/Content/theme/all.css")
    @Scripts.Render("~/bundles/js")

    @if (alternative)
    {
        <script>
            window.onload = function onLoad() {
                var bar = new ProgressBar.Line(container, {
                    strokeWidth: 4,
                    easing: 'easeInOut',
                    duration: 1400,
                    color: '@color',
                    trailColor: '@color',
                    trailWidth: 1,
                    svgStyle: { width: '100%', height: '100%' }
                });

                bar.animate(1.0);  // Number from 0.0 to 1.0
            };
        </script>

        <script>

            function closealert(element) {
                var main = document.getElementById("main");
                main.removeChild(element.parentNode);
            }
        </script>
    }

    <link href="@Url.Content("https://assets.utad.pt/css/Custom.css")" rel="stylesheet" type="text/css" />

    <link rel="shortcut icon" href="~/favicon.ico?v=3" />

    @RenderSection("Scripts", false)

</head>

<body>
    <div id="navBar">

        <div><a href="#anchor" class="firstAnchor"></a></div>

        <div id="navBarAPPS">
            <div tabindex="0" class="navBarAPPSOnClick">

                <img src=@Url.Content("~/Content/Images/appsicons.png") alt="Aplicações" style="cursor: pointer" class="noselect" />

                <ul class="navBarAPPSOnClickContentUl">
                    @{ Html.RenderPartial("_MenuAplicacoes", LayoutModel.Aplicacoes); }
                </ul>

            </div>
        </div>

        <div id='navBarAPPIcon-@ViewBag.Nome' class="navBarAPPIcon"><a href=@Url.Action("Index","Home") title='@appTitle'></a></div>

        <div id="navBarAPPTitle">
            <a @*href=@Url.Action("Index","Home")*@>
                <h1 class="noselect">@appTitle</h1>
            </a>
        </div>

        <label for="drop" class="MainToggle" ><img src=@Url.Content("~/Content/Images/menuresponsiveicon.png") alt="Menu"  class="noselect">m</label>

        <nav class="MainMenu">

            <input type="checkbox" id="drop" />

            <ul class="menu">
                @{ Html.RenderPartial("_MenuMenu", LayoutModel.Menu); }
            </ul>

        </nav>


        @if (Autenticacao.IsLoggedIn)
        {

            <div id="navBarAPPProfileIcon">

                <div tabindex="0" class="navBarAPPProfileIconOnClick">

                    @if (alternative)
                    {
                        <span class="glyphicon glyphicon-user"></span>
                    }
                    else
                    {
                        <img src=@Url.Content("~/Content/Images/iconPerfil.png") alt="Perfil" style="cursor: pointer" />
                    }

                    <div class="navBarAPPProfileIconContent">

                        <div id="navBarAPPProfileIconContentImg">
                            @if (imgSrc != null)
                            {
                                <img src=@imgSrc alt="Imagem de perfil" style="max-width: 50px;" />
                            }
                            else
                            {
                                <img src=@Url.Content("~/Content/Images/iconPerfil.png") alt="Imagem de perfil" />
                            }
                        </div>
                        <div id="navBarAPPProfileIconContentData">
                            <p>
                                @Autenticacao.NomeUtilizador
                            </p>
                            @if (Autenticacao.IsAluno)
                            {
                                <p>
                                    <label><b>Regime:</b></label>  @Autenticacao.Regime
                                </p>
                                <p>
                                    <label><b>Número:</b></label> @Autenticacao.Utilizador
                                </p>
                            }

                        </div>
                        <div id="navBarAPPProfileIconContentAction">
                            <a href=@Url.Action("Logout", "Session")>
                                Logout
                            </a>
                        </div>

                    </div>

                </div>
            </div>
        }
        else
        {
            <div id="navBarProfileLogin" style="background-color: @color;">
                <a href=@Url.Action("Index", "Secure")>
                    Iniciar Sessão
                </a>
            </div>
        }
        
        @if (LayoutModel.Linguagens != null && LayoutModel.Linguagens.Count() > 0)
        {
        <nav id="language">

            <ul class="menu">
                <li>
                    <label for='drop-X' class="toggle">@currentLanguage.texto</label>
                    
                    <a id="currentLanguage" title="@currentLanguage.title">@currentLanguage.texto @if(LayoutModel.Linguagens.Count() > 0) {<span class="glyphicon glyphicon-chevron-down"></span>}</a>

                    <input type="checkbox" id='drop-X' />
                    <ul id="languageSubMenu">
                        @{ Html.RenderPartial("_Linguagem", LayoutModel.Linguagens); }
                    </ul>

                </li>
            </ul>
        </nav>
        }

    </div>

    <a id="anchor"></a>

    @if (alternative)
    {
        <div id="container"></div>

        <div id="navBarAPPLine"></div>
    }
    else
    {
        <div id="navBarAPPLine-@ViewBag.Nome"></div>
    }

    <div id="wrap">

        <div id="main">
            @if (ViewBag.PageTitle != null && HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString().ToLower() != "home")
            {
                <h2 class="headerTitle">@ViewBag.PageTitle</h2>
            }

            @{ Html.RenderPartial("~/Views/Shared/_Mensagens.cshtml"); }

            @RenderBody()

        </div>
    </div>

    <footer class="footer">
        <div class="footerContainer">

            <div id="footerContainerText">
                <span><b><small>Universidade de Trás-os-Montes e Alto Douro - NSI 2017</small></b></span>
            </div>

            <div id="footerContainerImage">
                <img src=@Url.Content("~/Content/Images/qrenlogos.png") alt="QREN" />
            </div>

            <div id="wcag">
                <span>
                    <a href="http://www.w3.org/WAI/WCAG2AAA-Conformance" title="Explanation of WCAG 2.0 Level Triple-A Conformance">
                        <img height="32" width="88" src="http://www.w3.org/WAI/wcag2AAA" alt="Level Triple-A conformance, W3C WAI Web Content Accessibility Guidelines 2.0">
                    </a>
                </span>
            </div>

        </div>
    </footer>


</body>
</html>

Perfil/Views/Shared/_Linguagem.cshtml
@{
        foreach (var linguagem in Model)
        {
            <li>
                <a title="@linguagem.title" href="@linguagem.href">@linguagem.texto</a>
            </li>
        }
}

Perfil/Views/Shared/_Mensagens.cshtml
@{
    if (Convert.ToBoolean(System.Configuration.ConfigurationManager.AppSettings["AlternativeDesign"]))
    {
        if (TempData["warning"] != null && TempData["warning"] != "")
        {
            <div class="alerta alerta-warning">
                <button type="button" class="close" onclick="closealert(this)"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                @TempData["warning"]
            </div>
        }
        if (TempData["success"] != null && TempData["success"] != "")
        {
            <div class="alerta alerta-success">
                <button type="button" class="close" onclick="closealert(this)"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                @TempData["success"]
            </div>
        }
        if (TempData["info"] != null && TempData["info"] != "")
        {
            <div class="alerta alerta-info">
                <button type="button" class="close" onclick="closealert(this)"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                @TempData["info"]
            </div>
        }
        if (TempData["error"] != null && TempData["error"] != "")
        {
            <div class="alerta alerta-erro">
                <button type="button" class="close" onclick="closealert(this)"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                @TempData["error"]
            </div>
        }
    }
    else
    {
        if (TempData["warning"] != null && TempData["warning"] != "")
        {
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <span class="glyphicon glyphicon-warning-sign" style="font-size: 1.2em;"></span> <span style="white-space:pre-line"><strong> @TempData["warning"] </strong></span>
            </div>
        }
        if (TempData["success"] != null && TempData["success"] != "")
        {
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <span class="glyphicon glyphicon-ok-sign" style="font-size: 1.2em;"></span> <span style="white-space:pre-line"><strong> @TempData["success"] </strong></span>
            </div>
        }
        if (TempData["info"] != null && TempData["info"] != "")
        {
            <div class="alert alert-info alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <span class="glyphicon glyphicon-info-sign" style="font-size: 1.2em;"></span> <span style="white-space:pre-line"><strong> @TempData["info"] </strong></span>
            </div>
        }
        if (TempData["error"] != null && TempData["error"] != "")
        {
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <span class="glyphicon glyphicon-minus-sign" style="font-size: 1.2em;"></span> <span style="white-space:pre-line"><strong> @TempData["error"] </strong></span>
            </div>
        }
    }
}

Perfil/Views/Shared/_MenuAplicacoes.cshtml
@foreach (var item in Model as IEnumerable<Perfil.Models.Aplicacao>)
{
    <li class="navBarAPPSOnClickContentLi"><a id="navBarAPPSOnClickContent-@item.nome" href=@item.urlApp title="@item.titulo" target="_blank"></a></li>
}

Perfil/Views/Shared/_MenuMenu.cshtml
@{ 
    bool alternative = Convert.ToBoolean(System.Configuration.ConfigurationManager.AppSettings["AlternativeDesign"]);
}

@{
    int i = 0;

    foreach (var item in Model as IEnumerable<Perfil.Models.MenuItem>)
    {
        i++;
        <li>
            @if (@item.lstSubMenu != null && @item.lstSubMenu.Count != 0)
            {
                <label for='drop-@i' class="toggle">@item.Descricao </label>
            }

            @if (alternative)
            {
                <a title="@item.Descricao" href="@item.Url">
                    @item.Descricao @if (item.lstSubMenu != null && item.lstSubMenu.Count != 0)
                    {<span class="glyphicon glyphicon-chevron-down"></span>}
                </a>
            }
            else
            {
                <a title="@item.Descricao" href="@item.Url">@item.Descricao</a>
            }

            @if (@item.lstSubMenu != null && @item.lstSubMenu.Count != 0)
            {
                <input type="checkbox" id='drop-@i' />

                Html.RenderPartial("_MenuSubMenu", @item.lstSubMenu);
            }
        </li>
    }
}

Perfil/Views/Shared/_MenuSubMenu.cshtml
@{
    <ul>
        @foreach (var subitem in Model)
        {
            <li>
                <a href="@subitem.UrlSecond">@subitem.DescricaoSecond</a>
            </li>
        }
    </ul>
}